#!/bin/bash

#SBATCH --job-name mpi
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --time 00:10:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COSC028844
#SBATCH --output OUT.out
#SBATCH --cpus-per-task=1
#SBATCH --exclusive 


# Use Intel MPI (make sure you compile with the same module and 'mpiicc')
module load languages/intel/2018-u3


# Print some information about the job
echo "Running on host $(hostname)"
echo "Time is $(date)"
echo "Directory is $(pwd)"
echo "Slurm job ID is $SLURM_JOB_ID"
echo
echo "This job runs on the following machines:"
echo "$SLURM_JOB_NODELIST" | uniq
echo


# Enable using `srun` with Intel MPI
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

# Run the parallel MPI executable
mpirun ./hello_world_c.exe

